version: '3.7'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-airflow}
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-scheduler:
    image: apache/airflow:2.8.1-python3.11
    command: scheduler
    restart: always
    environment:
      &airflow-common
      AIRFLOW_DB_HOST: postgres
      AIRFLOW_DB_USER: ${POSTGRES_USER:-postgres}
      AIRFLOW_DB_PASS: ${POSTGRES_PASSWORD:-postgres}
      AIRFLOW_DB_NAME: ${POSTGRES_DB:-airflow}
      AIRFLOW_DB_PORT: 5432
      AIRFLOW_WEBSERVER_HOST: 0.0.0.0
      AIRFLOW_LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags  # Mount your DAGs folder
      - ./src:/opt/airflow/src    # Mount your SRC folder
      - ./data:/opt/airflow/data  # Mount your DATA folder
      - ./requirements.txt:/requirements.txt # Mount dependencies
    depends_on:
      postgres:
        condition: service_healthy
    # Install Python dependencies at startup
    user: "${AIRFLOW_UID:-50000}:0"
    entrypoint: /bin/bash -c "pip install --no-cache-dir -r /requirements.txt && /entrypoint.sh"

  airflow-webserver:
    image: apache/airflow:2.8.1-python3.11
    command: webserver
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      airflow-scheduler:
        condition: service_started
    environment:
      <<: *airflow-common # Inherit common Airflow settings
    user: "${AIRFLOW_UID:-50000}:0"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./requirements.txt:/requirements.txt